FITorg.Web/Areas/AdminUser/Controllers/DrzaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FITorg.Data;
using FITorg.Data.EntityModels;
using FITorg.Web.Areas.AdminUser.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;


//Drzave kontroler se brine upravljanjem drzava iz admin panela
namespace FITorg.Web.Areas.AdminUser.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("AdminUser")]
    public class DrzaveController : Controller
    {
        private MyContext _context;

        public DrzaveController(MyContext context)
        {
            _context = context;
        }
        // GET: DrzaveController
        public ActionResult Index()
        {
            DrzaveIndexVM model = new DrzaveIndexVM()
            {
                Rows = _context.Drzava.Select(x => new DrzaveIndexVM.Row()
                {
                    DrzavaId = x.DrzavaId,
                    Naziv = x.Naziv
                }).ToList()
            };
            return View(model);
        }

        public ActionResult Dodaj()
        {
            DrzaveDodajVM model = new DrzaveDodajVM();
            return View(model);
        }
        [HttpPost]
        public IActionResult Dodaj(DrzaveDodajVM vm)
        {
            Drzava r = _context.Drzava.Where(a => a.DrzavaId == vm.DrzavaId).FirstOrDefault();

            if (r == null)
            {
                Drzava a = new Drzava
                {
                    DrzavaId = vm.DrzavaId,
                    Naziv = vm.Naziv
                };
                _context.Drzava.Add(a);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            r.DrzavaId = vm.DrzavaId;
            r.Naziv = vm.Naziv;


            _context.SaveChanges();
            _context.Dispose();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Uredi(int id)
        {
            DrzaveDodajVM model = new DrzaveDodajVM();
            model.DrzavaId = id;
            model.Naziv = _context.Drzava.Where(a => a.DrzavaId == model.DrzavaId).SingleOrDefault().Naziv;
            return View(model);
        }

        public IActionResult Obrisi(int Id)
        {
            Drzava x = _context.Drzava.Find(Id);
            _context.Drzava.Remove(x);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FITorg.Web/Areas/AdminUser/Views/Drzave/Dodaj.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.DrzaveDodajVM
@{
    ViewData["Title"] = "Fitorg";
    Layout = "_LayoutAdmin";
}
<h2>Dodajte novu državu</h2>
<form asp-action="Dodaj" asp-controller="Drzave" method="post">
    <input type="hidden" value="@Model.DrzavaId" name="DrzavaId" />
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label>Naziv države: </label>
                <input asp-for="@Model.Naziv" class="form-control  col-md-12" type="text" placeholder="Unesite naziv države: " required />
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success">Spremi</button>
</form>

FITorg.Web/Areas/AdminUser/Views/Drzave/Index.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.DrzaveIndexVM
@{
    ViewData["Title"] = "Fitorg";
    Layout = "_LayoutAdmin";
}
<h2>Lista država</h2>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Lista drzava za odabir
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Naziv</th>
                    <th>Akcije</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var x in Model.Rows)
                {
                    <tr>
                        <td style="width: 80%">@x.Naziv</td>
                        <td>
                            <a asp-action="Uredi" asp-controller="Drzave" asp-route-id="@x.DrzavaId" class="btn btn-info font-sizes"><i class="fas fa-edit icons-margin-right"></i> Uredi </a>
                            <a asp-action="Obrisi" asp-controller="Drzave" asp-route-id="@x.DrzavaId" class="btn btn-danger font-sizes"><i class="fas fa-minus icons-margin-right"></i> Obriši </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
<a asp-action="Dodaj" asp-controller="Drzave" class="btn btn-success  col-md-2 font-sizes float-right"><i class="fas fa-plus-circle icons-margin-right"></i> Dodaj državu</a>

FITorg.Web/Areas/AdminUser/Views/Drzave/Uredi.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.DrzaveDodajVM
@{
    ViewData["Title"] = "Fitorg";
    Layout = "_LayoutAdmin";
}
<h2>Uredite državu</h2>
<form asp-action="Dodaj" asp-controller="Drzave" method="post">
    <input type="hidden" value="@Model.DrzavaId" name="DrzavaId" />
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label>Naziv države: </label>
                <input asp-for="@Model.Naziv" class="form-control  col-md-12" type="text" placeholder="Unesite naziv države: " required />
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success">Spremi</button>
</form>