FITorg.Web/Areas/TrUser/Controllers/VjezbeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FITorg.Data;
using FITorg.Data.EntityModels;
using FITorg.Web.Areas.TrUser.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

//Area za korisnika tipa Trener
namespace FITorg.Web.Areas.TrUser.Controllers
{
    [Authorize(Roles = "Trener")]
    [Area("TrUser")]

    public class VjezbeController : Controller
    {
        private MyContext _db;
        // GET: HomeController
        public VjezbeController(MyContext context)
        {
            _db = context;
        }
        public ActionResult Index(string idStr,int idInt)
        {
            if (idStr != null)
            {
                Trener t = _db.Trener.Where(x => x.AppUserId == int.Parse(idStr)).FirstOrDefault();

                VjezbeIndexVM model = new VjezbeIndexVM()
                {
                    Rows = _db.Vjezba.Where(a => a.TrenerId == t.TrenerId).Select(v => new VjezbeIndexVM.Row()
                    {
                        VjezbaId = v.VjezbaId,
                        Naziv = v.Naziv,
                        videoUrl = v.VideoUrl
                    }).ToList()
                };
                return View(model);
            }
            else
            {
                VjezbeIndexVM model = new VjezbeIndexVM()
                {
                    Rows = _db.Vjezba.Where(a => a.TrenerId == idInt).Select(v => new VjezbeIndexVM.Row()
                    {
                        VjezbaId = v.VjezbaId,
                        Naziv = v.Naziv,
                        videoUrl = v.VideoUrl
                    }).ToList()
                };
                return View(model);
            }
        }


        // GET: HomeController/Dodaj (prima trener id)
        public ActionResult Dodaj(string id)
        {
            VjezbeDodajVM model = new VjezbeDodajVM();
            model.AppUserId=int.Parse(id);
            return View(model);
        }

        // POST: HomeController/Dodaj
        [HttpPost]
        public ActionResult Dodaj(VjezbeDodajVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Vjezba v = new Vjezba
            {
                Naziv = vm.Naziv,
                TrenerId = _db.Trener.Where(x=>x.AppUserId == vm.AppUserId).Select(x=>x.TrenerId).FirstOrDefault(),
                VideoUrl = vm.videoUrl
            };
            _db.Add(v);
            _db.SaveChanges();
            _db.Dispose();

            return RedirectToAction(nameof(Index),new{idInt=v.TrenerId});
            
        }

        // GET: HomeController/Uredi
        public ActionResult Uredi(int id)
        {
            VjezbeDodajVM model =new VjezbeDodajVM();
            Vjezba v = _db.Vjezba.Find(id);
            model.Naziv = v.Naziv;
            model.videoUrl = v.VideoUrl;
            model.VjezbaId = v.VjezbaId;
            return View(model);
        }

        // POST: HomeController/Uredi
        [HttpPost]
        public ActionResult Uredi(VjezbeDodajVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            Vjezba v = _db.Vjezba.Find(vm.VjezbaId);
            v.Naziv = vm.Naziv;
            v.VideoUrl = vm.videoUrl;
            _db.SaveChanges();
            _db.Dispose();
            return RedirectToAction(nameof(Index),new{idInt=v.TrenerId});
          
        }

        // GET: HomeController/Delete/5
        public ActionResult Obrisi(int id)
        {
            int trenerId = _db.Vjezba.Where(x => x.VjezbaId == id).Select(x => x.TrenerId).FirstOrDefault();
            Vjezba v = _db.Vjezba.Find(id);
            _db.Remove(v);
            _db.SaveChanges();
            _db.Dispose();
            return RedirectToAction(nameof(Index),new{trenerId});

        }

        public ActionResult PrikaziVideoPV(string url)
        {
            string pomocni = "watch?v=";
            string code = url.Split(pomocni, StringSplitOptions.None).Last();

            TempData["urlcode"] = code;
            return PartialView();
        }
    }
}

FITorg.Web/Areas/TrUser/Views/Shared/_LayoutTrener.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@using FITorg.Data.EntityModels
@using System.Security.Claims
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Dashboard - Trener</title>
    <link href="~/AdminPanel/dist/css/styles.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous" asp-append-version="true"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-light bg-light">
        <div style="width: 200px;height: 62px" align="center"><img src="\images\logo2.png" width="120" height="60" style="position: center" /></div>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input hidden="hidden" class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button" hidden="hidden"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="ChangePassword" asp-route-id="@this.User.FindFirstValue(ClaimTypes.NameIdentifier)">Change password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/TwoFactorAuthentication">2way authentication</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <!-- Sidenav_navbar-->
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a asp-area="TrUser" asp-controller="Home" asp-action="Index" asp-route-id="@int.Parse(this.User.FindFirstValue(ClaimTypes.NameIdentifier) )"   class="nav-link">
                            <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                            Home
                        </a>
                        <div class="sb-sidenav-menu-heading">Menu</div>
                        <!-- Sportaši-->
                        <a asp-area="TrUser" asp-controller="Sportasi" asp-action="Index" class="nav-link collapsed">
                            <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                            Sportaši
                        </a>
                        <!-- Vjezbe-->
                        <a asp-area="TrUser" asp-controller="Vjezbe" asp-action="Index" asp-route-idStr="@this.User.FindFirstValue(ClaimTypes.NameIdentifier)" class="nav-link collapsed">
                            <div class="sb-nav-link-icon"><i class="fas fa-bicycle"></i></div>
                            Vjezbe
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    @User.Identity.Name
                </div>
            </nav>
        </div>
        <!-- Sidenav_content-->
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Fitorg</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/AdminPanel/dist/js/scripts.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/AdminPanel/dist/assets/demo/chart-area-demo.js" asp-append-version="true"></script>
    <script src="~/AdminPanel/dist/assets/demo/chart-bar-demo.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous" asp-append-version="true"></script>
    <script src="~/AdminPanel/dist/assets/demo/datatables-demo.js" asp-append-version="true"></script>
    <script src="~/LoginFront/js/main.js"></script>
    <script src="~/AdminPanel/dist/js/jsFIT.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>