FITorg.Web/Areas/AdminUser/Controllers/GradoviController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FITorg.Data;
using FITorg.Data.EntityModels;
using FITorg.Web.Areas.AdminUser.ViewModels;
using FITorg.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;


//Drzave kontroler se brine upravljanjem drzava iz admin panela
namespace FITorg.Web.Areas.AdminUser.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("AdminUser")]
    public class GradoviController : Controller
    {
        private MyContext _db;

        public GradoviController(MyContext context)
        {
            _db = context;
        }
        // GET: DrzaveController
        public ActionResult Index()
        {
            GradoviIndexVM model = new GradoviIndexVM()
            {
                Rows = _db.Grad.Select(x => new GradoviIndexVM.Row()
                {
                    GradId = x.GradId,
                    Naziv = x.Naziv,
                    NazivDrzave = x.Drzava.Naziv
                }).ToList()
            };
            return View(model);
        }

        public ActionResult Dodaj()
        {
            GradoviDodajVM vm = new GradoviDodajVM();
            vm.DrzaveItems = _db.Drzava.Select(o => new SelectListItem(o.Naziv, o.DrzavaId.ToString())).ToList();
            return View("Dodaj", vm);
        }

        [HttpPost]
        public IActionResult Dodaj(GradoviDodajVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View("Dodaj", vm);
            }
            Grad g = _db.Grad.Where(a => a.GradId == vm.GradId).SingleOrDefault();
            if (g == null)
            {
                Grad a = new Grad
                {
                    GradId = vm.GradId,
                    DrzavaId = vm.DrzavaId,
                    Naziv = vm.Naziv
                };
                _db.Grad.Add(a);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            g.GradId = vm.GradId;
            g.Naziv = vm.Naziv;
            g.DrzavaId = vm.DrzavaId;

            _db.SaveChanges();
            _db.Dispose();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Uredi(int id)
        {
            GradoviDodajVM model = new GradoviDodajVM();
            model.GradId = id;
            model.Naziv = _db.Grad.Where(a => a.GradId == model.GradId).SingleOrDefault().Naziv;
            model.DrzavaId = _db.Grad.Where(a => a.GradId == id).SingleOrDefault().DrzavaId;
            model.DrzaveItems = _db.Drzava.Select(o => new SelectListItem(o.Naziv, o.DrzavaId.ToString())).ToList();

            return View(model);
        }

        public ActionResult Obrisi(int Id)
        {
            Grad x = _db.Grad.Find(Id);
            _db.Grad.Remove(x);
            _db.SaveChanges();
            _db.Dispose();
            return RedirectToAction("Index");
        }
    }
}

FITorg.Web/Areas/AdminUser/Views/Gradovi/Dodaj.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.GradoviDodajVM
@{ ViewData["Title"] = "TravelEurope";
                Layout = "_LayoutAdmin";

}
<h2>Dodajte novi grad</h2>
<form asp-action="Dodaj" method="post">
    <input type="hidden" value="@Model.GradId" name="GradId" />
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.Naziv">Naziv grada</label>
                <input asp-for="@Model.Naziv" class="form-control  col-md-12" type="text" placeholder="Unesite naziv grada: " required />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.DrzavaId">Izaberite državu</label>
                <select asp-for="@Model.DrzavaId" asp-items="@Model.DrzaveItems" class="form-control col-md-12">
                    <option value="">Odaberite drzavu</option>
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Sačuvaj</button>
    </div>
</form>

FITorg.Web/Areas/AdminUser/Views/Gradovi/Index.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.GradoviIndexVM
@{
    ViewData["Title"] = "Fitorg";
    Layout = "_LayoutAdmin";
}
<h2>Lista gradova</h2>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Lista gradova za odabir
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Naziv</th>
                        <th>Drzava</th>
                        <th>Akcije</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var x in Model.Rows)
                {
                    <tr>
                        <td style="width: 38%">@x.Naziv</td>
                        <td style="width: 38%">@x.NazivDrzave</td>
                        <td>
                            <a asp-action="Uredi" asp-controller="Gradovi" asp-route-id="@x.GradId" class="btn btn-info font-sizes"><i class="fas fa-edit icons-margin-right"></i> Uredi</a>
                            <a asp-action="Obrisi" asp-controller="Gradovi" asp-route-id="@x.GradId" class="btn btn-danger font-sizes"><i class="fas fa-minus icons-margin-right"></i> Obriši</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
<a asp-action="Dodaj" asp-controller="Gradovi" class="btn btn-success  col-md-2 font-sizes float-right"><i class="fas fa-plus-circle icons-margin-right"></i> Dodaj grad</a>

FITorg.Web/Areas/AdminUser/Views/Gradovi/Uredi.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.GradoviDodajVM
@{
    ViewData["Title"] = "Fitorg";
    Layout = "_LayoutAdmin";
}
<h2>Uredite @Model.Naziv</h2>
<form asp-action="Dodaj" asp-controller="Gradovi" method="post">
    <input type="hidden" value="@Model.GradId" name="GradId" />
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.Naziv">Naziv grada</label>
                <input asp-for="@Model.Naziv" class="form-control  col-md-12" type="text" placeholder="Unesite naziv grada: " required />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.DrzavaId">Izaberite državu</label>
                <select asp-for="@Model.DrzavaId" asp-items="@Model.DrzaveItems" class="form-control col-md-12">
                    <option value="">Odaberite drzavu</option>
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Spremi</button>
    </div>
</form>