FITorg.Web/Areas/AdminUser/Controllers/TreneriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using FITorg.Data;
using FITorg.Data.EntityModels;
using FITorg.Web.Areas.AdminUser.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;


namespace FITorg.Web.Areas.AdminUser.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("AdminUser")]
    public class TreneriController : Controller
    {
        private MyContext _db;

        private readonly UserManager<AppUser> _userMgr;

        public TreneriController(MyContext context, UserManager<AppUser> userManager)
        {
            _db = context;
            _userMgr = userManager;
        }
        // GET: TreneriController
        public ActionResult Index()
        {
            TreneriIndexVM model = new TreneriIndexVM()
            {
                Rows = _db.Trener.Select(x=> new TreneriIndexVM.Row()
                {
                    TrenerId = x.TrenerId,
                    ImePrezime = x.AppUser.Ime +" "+x.AppUser.Prezime,
                    email = x.AppUser.Email,
                    NazivGrada = x.AppUser.Grad.Naziv,
                    NazivDrzave = x.AppUser.Drzava.Naziv,
                    Spol = x.AppUser.Spol.Naziv
                }).ToList()
            };
            return View(model);
        }

       

        // GET: TreneriController/Edit
        public ActionResult Uredi(int id)
        {
            
            Trener t = _db.Trener.Where(t => t.TrenerId == id).Include(a => a.AppUser).
                        Include(x=>x.AppUser.Drzava).FirstOrDefault();
            TreneriUrediVM model = new TreneriUrediVM();

            model.TrenerID = id;
            model.Ime = t.AppUser.Ime;
            model.Prezime = t.AppUser.Prezime;
            model.Email = t.AppUser.Email;
            model.Mob = t.AppUser.PhoneNumber;
            model.DatumRodjenja = t.AppUser.DatumRodjenja;
            model.GradId = t.AppUser.GradId;
            model.Drzava = t.AppUser.Drzava.Naziv;
            model.SpolId = t.AppUser.SpolId;
            model.GradoviItems = _db.Grad.Select(g => new SelectListItem(g.Naziv, g.GradId.ToString())).ToList();
            model.SpolItems = _db.Spol.Select(g => new SelectListItem(g.Naziv, g.SpolId.ToString())).ToList();

            return View(model);
        }

        // POST: TreneriController1/Create
        [HttpPost]
        public async Task<ActionResult> Uredi(TreneriUrediVM vm)
        {
           
            
            
            var userE = await _userMgr.FindByEmailAsync(vm.Email);
            int id = _db.Trener.Where(x => x.TrenerId == vm.TrenerID).Select(x => x.AppUserId).FirstOrDefault();
            if (userE != null && userE.Id!=id)
            {
                TempData["poruka"] = "Email already in use. ";
                return RedirectToAction("Uredi",new{id=vm.TrenerID});
            }
            
            Trener t = _db.Trener.Where(d => d.TrenerId == vm.TrenerID).Include(a =>a.AppUser).SingleOrDefault();

            t.AppUser.Ime = vm.Ime;
            t.AppUser.Prezime = vm.Prezime;
            t.AppUser.Email = vm.Email;
            t.AppUser.PhoneNumber = vm.Mob;
            t.AppUser.DatumRodjenja = vm.DatumRodjenja;
            t.AppUser.GradId = vm.GradId;
            t.AppUser.DrzavaId = _db.Grad.Where(x => x.GradId == vm.GradId).Select(x => x.DrzavaId).FirstOrDefault();
            t.AppUser.SpolId = vm.SpolId;

            _db.SaveChanges();
            _db.Dispose();

            return RedirectToAction(nameof(Index));

        }

        

        // GET: TreneriController1/Delete/5
        public IActionResult Obrisi(int id)
        {
            Trener t = _db.Trener.Find(id);
            AppUser u = _db.Users.Find(t.AppUserId);
            _db.Remove(t);
            _db.Remove(u);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        
        
    }
}

FITorg.Web/Areas/AdminUser/Views/Treneri/Index.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.TreneriIndexVM
@{
    ViewData["Title"] = "Fitorg";
    Layout = "_LayoutAdmin";
}
<h2>Lista trenera</h2>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Lista trenera koji koriste aplikaciju
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Ime i prezime</th>
                        <th>E-mail</th>
                        <th>Grad</th>
                        <th>Drzava</th>
                        <th>Spol</th>
                        <th>Akcije</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var x in Model.Rows)
                {
                    <tr>
                        <td style="width: 19%">@x.ImePrezime</td>
                        <td style="width: 19%">@x.email</td>
                        <td style="width: 10%">@x.NazivGrada</td>
                        <td style="width: 17%">@x.NazivDrzave</td>
                        <td style="width: 5%">@x.Spol</td>
                        <td>
                            <a asp-action="Uredi" asp-controller="Treneri" asp-route-id="@x.TrenerId" class="btn btn-info font-sizes"><i class="fas fa-edit icons-margin-right"></i> Uredi</a>
                            <a asp-action="Obrisi" asp-controller="Treneri" asp-route-id="@x.TrenerId" class="btn btn-danger font-sizes"><i class="fas fa-minus icons-margin-right"></i> Obriši</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

FITorg.Web/Areas/AdminUser/Views/Treneri/Uredi.cshtml
@model FITorg.Web.Areas.AdminUser.ViewModels.TreneriUrediVM
@{
    ViewData["Title"] = "Fitorg";
    Layout = "_LayoutAdmin";
    var poruka = (string)TempData["poruka"];

}
@if (poruka != null)
{
    <div class="alert alert-success" role="alert" id="porukaBox">
        @poruka
    </div>
}
<h2>Uredite @Model.Ime @Model.Prezime</h2>
<form asp-action="Uredi" asp-controller="Treneri" method="post">
    <input type="hidden" value="@Model.TrenerID" asp-for="TrenerID" />
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.Ime">Ime</label>
                <input asp-for="@Model.Ime" class="form-control  col-md-12" type="text" placeholder="@Model.Ime " required />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.Prezime">Prezime</label>
                <input asp-for="@Model.Prezime" class="form-control  col-md-12" type="text" placeholder="@Model.Prezime" required />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.Email">E-mail</label>
                <input asp-for="@Model.Email" class="form-control  col-md-12" type="email" placeholder="@Model.Email" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.DatumRodjenja">Datum rođenja</label>
                <input asp-for="@Model.DatumRodjenja" class="form-control  col-md-12" type="date" placeholder="@Model.DatumRodjenja" required />
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.GradId">Grad</label>
                <select asp-for="@Model.GradId" asp-items="@Model.GradoviItems" class="form-control select2-container">
                    <option value="">Odaberite grad</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label>Država</label>
                <span class="form-control col-md-12">@Model.Drzava</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12 form-group">
                <label asp-for="@Model.SpolId">Spol</label>
                <select asp-for="@Model.SpolId" asp-items="@Model.SpolItems" class="form-control select2-container">
                    <option value="">Odaberite spol</option>
                </select>
            </div>
        </div>
        <button type="submit" class="btn btn-success">Spremi</button>
    </div>
</form>